name = "discordlookup-testflight-watcher"
main = "src/worker.ts"
compatibility_date = "2025-06-21"

account_id = ""
workers_dev = true

#route = "https://testflight-worker.khamphatestflight.workers.dev/"

[vars]
#TESTFLIGHT_URL = ""
DISCORD_WEBHOOK_URL = ""

[triggers]
crons = ["*/1 * * * *"]

[[r2_buckets]]
binding = "STATE_BUCKET"
bucket_name = "testflight-state"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
head_sampling_rate = 0.2