name = "discordlookup-testflight-watcher"
main = "src/worker.ts"
compatibility_date = "2025-06-21"

account_id = ""
workers_dev = true

#route = "https://testflight-worker.khamphatestflight.workers.dev/"

[vars]
TESTFLIGHT_URL = "https://testflight.apple.com/join/dDtSst46"
DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/"

[triggers]
crons = ["*/1 * * * *"]

[[r2_buckets]]
binding = "STATE_BUCKET"
bucket_name = "testflight-state"
